# Generated by Django 3.2 on 2021-04-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_isbn_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='isbn',
            name='author_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
